
spring:
  profiles:
    active: ${DEPLOYMENT_STAGE:dev}
  application:
    name: curricula-service

  
    
---
spring:
  profiles: dev    
  datasource:
    driverClassName: org.h2.Driver
    platform: h2
    url: jdbc:h2:mem:curricula;Mode=PostgreSQL
    initilize: true
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 1910
---
spring:
  profiles: uat    
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:curricula_service}
    show-sql: false
server:
  port: 8080   
