version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: |
           cd ./CurriculaService
           mvn verify sonar:sonar

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
          context: SonarCloud